/**
 * Banco de 100 ideias de date para a Raspadinha.
 * Cada quadradinho esconde uma dessas ideias.
 */
export const SCRATCH_IDEAS: string[] = [
  'Observar as estrelas',
  'Maratona de filmes',
  'Visitar uma livraria',
  'Dirigir por paisagens bonitas',
  'Jogar videogame juntos',
  'Planejar uma viagem futura',
  'Assistir a um jogo esportivo',
  'Montar um quebra-cabeça',
  'Visitar um festival local',
  'Assistir ao nascer do sol',
  'Assistir ao pôr do sol',
  'Ir ao cinema drive-in',
  'Explorar uma cidade nova',
  'Passeio fotográfico',
  'Ser voluntários juntos',
  'Empinar pipa',
  'Criar um álbum de recortes',
  'Andar de bicicleta',
  'Experimentar um restaurante novo',
  'Criar uma cápsula do tempo',
  'Fazer uma lista de desejos',
  'Visitar um centro de ciências',
  'Planejar um encontro surpresa',
  'Assistir a vídeos em casa',
  'Caçar conchas na praia',
  'Cozinhar um jantar a dois',
  'Realizar um sonho em comum',
  'Passeio noturno',
  'Passeio de barco',
  'Noite de vinhos',
  'Visitar uma cachoeira',
  'Fondue com karaokê',
  'Café da tarde ao ar livre',
  'Jantar temático',
  'Acampamento romântico',
  'Sessão de cinema caseiro',
  'Vinho e fogueira',
  'Escrever cartas um para o outro',
  'Trocar livros favoritos',
  'Montar uma playlist juntos',
  'Assistir ao pôr do sol em um mirante',
  'Fazer um café da manhã especial juntos',
  'Aprender uma receita totalmente nova',
  'Passear com um pet em um parque',
  'Visitar uma floricultura',
  'Conhecer um bairro novo da cidade',
  'Passeio de scooter elétrica',
  'Fazer um desafio de culinária',
  'Criar uma playlist da relação',
  'Escrever metas para o próximo ano',
  'Comprar ingredientes vendados e cozinhar',
  'Jogar perguntas e respostas sobre o casal',
  'Montar um LEGO juntos',
  'Ir a uma cafeteria temática',
  'Tomar sorvete caminhando pela cidade',
  'Visitar um observatório',
  'Passear em uma praça histórica',
  'Ver um show de luzes',
  'Fazer um tour gastronômico de sobremesas',
  'Assistir a um musical',
  'Fazer um brunch em casa',
  'Criar um mural de fotos',
  'Montar uma playlist para viajar',
  'Aprender origami juntos',
  'Fazer uma guerra de balões de água',
  'Brincar de caça ao tesouro',
  'Montar uma barraca na sala e acampar dentro de casa',
  'Fazer cookies ou brownies juntos',
  'Ir a uma loja de discos ou vinis',
  'Assistir à chuva com chocolate quente',
  'Escrever uma história juntos',
  'Fazer um tour pelas cafeterias da cidade',
  'Experimentar comidas de um país diferente',
  'Criar um desafio de fotos engraçadas',
  'Passear sem destino de carro',
  'Fazer um diário de aventuras do casal',
  'Assistir a um documentário e conversar sobre ele',
  'Piquenique no parque',
  'Jantar à luz de velas em casa',
  'Aula de culinária juntos',
  'Tarde em um café charmoso',
  'Show ao vivo',
  'Noite de jogos de tabuleiro',
  'Degustação de cervejas artesanais',
  'Escape room',
  'Aula de dança',
  'Visitar um jardim botânico',
  'Trilha ao nascer do sol',
  'Passeio de bicicleta pela cidade',
  'Dia de spa em casa',
  'Aula de pintura em tela',
  'Tarde na praia',
  'Noite de karaokê',
  'Visitar um mercado de antiguidades',
  'Tour por bairro histórico',
  'Tarde de boliche',
  'Noite de degustação de queijos',
  'Sessão de fotos urbana',
  // Novas ideias — lote 2
  'Fazer um picnic ao pôr do sol',
  'Visitar uma feira de artesanato',
  'Assistir a uma peça de teatro',
  'Tatuar algo juntos (henna ou de verdade)',
  'Explorar um parque nacional',
  'Alugar um caiaque ou stand-up paddle',
  'Visitar um aquário',
  'Fazer uma degustação de azeites ou cafés especiais',
  'Dançar em casa sem motivo nenhum',
  'Assistir a um filme mudo com trilha sonora ao vivo',
  'Visitar uma exposição de arte contemporânea',
  'Cozinhar a receita favorita da infância de cada um',
  'Fazer uma noite de leitura compartilhada',
  'Comprar algo em um sebo e trocar os livros',
  'Visitar um zoológico ou santuário de animais',
  'Fazer um tour de bike noturno',
  'Assistir ao amanhecer num mirante',
  'Explorar uma feira de gastronomia de rua',
  'Assistir a uma partida de xadrez ao vivo',
  'Montar um terrário ou jardim em vaso juntos',
  'Criar um ritual de domingo só de vocês dois',
  'Fazer um desafio de arte: cada um retrata o outro',
  'Visitar uma ponte ou lugar icônico da cidade à noite',
  'Jogar bocha, petanca ou frescobol na praça',
  'Assistir a uma sessão de cinema ao ar livre',
  'Fazer uma aula de ioga ou pilates juntos',
  'Visitar um museu a dois',
  'Explorar um bairro só de cabeça para baixo — sem GPS',
  'Fazer o café da manhã favorito do outro com surpresa',
  'Assistir a um concerto de música clássica ou jazz',
  'Fazer uma noite temática de um país: comida, filme, música',
  'Criar um jogo de perguntas e desafios personalizado',
  'Visitar um mercadinho orgânico e cozinhar com o que achar',
  'Fazer uma caminhada na chuva com guarda-chuva e café quente',
  'Assistir ao lance do gol de um jogo em bar movimentado',
  'Registrar o dia inteiro em fotos analógicas',
  'Montar uma horta de temperos em casa',
  'Fazer um desafio de arte: aquarela, colagem ou argila',
  'Visitar uma vinícola ou cervejaria artesanal',
  'Explorar uma trilha com cachoeira no fim',
  'Criar um ritual de sexta-feira só de vocês',
  'Ir a um drive-in de carro antigo',
  'Fazer uma aula de surf, stand-up ou esportes aquáticos',
  'Passear de teleférico ou bondinho',
  'Visitar um parque de esculturas',
  'Fazer um churrasco para os dois com tudo do jeito certo',
  'Assistir a uma apresentação de dança contemporânea',
  'Visitar um castelo, fazenda histórica ou sítio arqueológico',
  'Fazer uma caminhada noturna numa praia deserta',
  'Montar um álbum físico com fotos impressas dos melhores momentos',
]
