/**
 * Banco de 100 ideias de date para a Raspadinha.
 * Cada quadradinho esconde uma dessas ideias.
 */
export const SCRATCH_IDEAS: string[] = [
  'Piquenique ao pôr do sol com vista panorâmica',
  'Maratona de filmes de uma década específica',
  'Visitar uma livraria e comprar um livro para o outro',
  'Dirigir sem destino ouvindo um podcast de true crime',
  'Jogar videogame cooperativo ou de luta',
  'Planejar a viagem dos sonhos com mapa e roteiro',
  'Assistir a um jogo em um bar com torcida',
  'Montar um quebra-cabeça de 1000 peças com música tema',
  'Visitar uma feira de artesanato local',
  'Caminhar ao nascer do sol e tomar café em padaria 24h',
  'Assistir ao pôr do sol em um mirante famoso',
  'Ir a um cinema drive-in',
  'Explorar um bairro novo sem destino',
  'Fazer um desafio de fotos em lugares bonitos',
  'Ser voluntários em uma causa social juntos',
  'Empinar pipa em um dia de vento',
  'Criar um mural de fotos da relação',
  'Andar de bicicleta pela orla da cidade',
  'Experimentar um restaurante de um país diferente',
  'Montar uma cápsula do tempo com objetos de 2026',
  'Criar uma lista de desejos para os próximos 5 anos',
  'Visitar um centro de ciências interativo',
  'Planejar um encontro surpresa para o outro',
  'Assistir a vídeos antigos e relembrar momentos',
  'Caçar conchas e pedras na praia',
  'Cozinhar um jantar a dois com receita nova',
  'Realizar um sonho em comum',
  'Passeio noturno de bicicleta pela cidade',
  'Alugar um caiaque ou stand-up paddle',
  'Noite de degustação de vinhos em casa',
  'Visitar uma cachoeira escondida',
  'Fondue de queijo ou chocolate com frutas',
  'Brunch em uma cafeteria com vista para a rua',
  'Jantar temático com filme do mesmo país',
  'Acampar no quintal com marshmallows',
  'Sessão de cinema caseiro com pipoca gourmet',
  'Vinho e fogueira na lareira',
  'Escrever cartas de amor para abrir em 10 anos',
  'Trocar livros favoritos e discutir depois',
  'Montar uma playlist colaborativa da relação',
  'Observar estrelas com chocolate quente',
  'Fazer um café da manhã especial na cama',
  'Aprender uma receita totalmente nova juntos',
  'Passear com um pet em um parque',
  'Visitar uma floricultura e comprar flores',
  'Conhecer um café temático (de gatos, jogos ou vintage)',
  'Passeio de scooter elétrica pela cidade',
  'Fazer um desafio MasterChef com ingredientes baratos',
  'Criar uma playlist com músicas do relacionamento',
  'Escrever metas e sonhos para o próximo ano',
  'Comprar ingredientes vendados e cozinhar',
  'Jogar perguntas profundas sobre o casal',
  'Montar um LEGO Arquitetura juntos',
  'Ir a uma cafeteria nova e provar doces diferentes',
  'Tomar sorvete caminhando pelas ruas',
  'Visitar um planetário ou observatório',
  'Passear em uma praça histórica',
  'Fazer um tour gastronômico de sobremesas',
  'Assistir a um musical ou peça de teatro',
  'Fazer um piquenique noturno com lanternas',
  'Criar um álbum físico com fotos impressas',
  'Montar uma playlist para uma viagem futura',
  'Aprender origami e fazer aviões de papel',
  'Guerra de balões de água no verão',
  'Caça ao tesouro dentro de casa com pistas',
  'Montar uma barraca na sala e acampar dentro de casa',
  'Fazer cookies ou brownies e decorar juntos',
  'Ir a uma loja de discos de vinil',
  'Assistir à chuva com chocolate quente',
  'Escrever uma história maluca juntos (parágrafo alternado)',
  'Fazer um tour pelas cafeterias da cidade',
  'Experimentar comidas de rua em uma feira gastronômica',
  'Criar um desafio de fotos engraçadas',
  'Passear de carro sem destino',
  'Fazer um diário de aventuras do casal',
  'Assistir a um documentário e teorizar sobre ele',
  'Piquenique no parque com vista para o lago',
  'Jantar à luz de velas em casa',
  'Aula de culinária de um país que querem visitar',
  'Tarde em um café charmoso com jogos de tabuleiro',
  'Show ao vivo de música ou comédia',
  'Noite de jogos de tabuleiro com petiscos',
  'Degustação de cervejas artesanais em casa',
  'Escape room para dois',
  'Aula de dança (salsa, forró ou tango)',
  'Visitar um jardim botânico',
  'Trilha leve ao nascer do sol',
  'Passeio de bicicleta por um bairro histórico',
  'Dia de spa em casa com massagem e máscara',
  'Aula de pintura em tela com vinho',
  'Tarde na praia com livros e música',
  'Noite de karaokê com dublagem e dança',
  'Visitar um mercado de antiguidades',
  'Tour por um bairro histórico com guia',
  'Tarde de boliche com apostas bobas',
  'Noite de degustação de queijos e vinhos',
  'Sessão de fotos urbana em lugares icônicos',
  'Noite de Drink & Draw (desenhar um ao outro)',
  'Customizar camisetas brancas com tinta',
  'Fazer um terrário ou jardim suculento juntos',
  'Assistir a um concerto de jazz intimista',
  'Dormir na sala com pipoca e filmes antigos'
]