/**
 * Banco de 100 ideias de date para a Raspadinha.
 * Cada quadradinho esconde uma dessas ideias.
 */
export const SCRATCH_IDEAS: string[] = [
  'Observar as estrelas',
  'Maratona de filmes',
  'Visitar uma livraria',
  'Dirigir por paisagens bonitas',
  'Jogar videogame juntos',
  'Planejar uma viagem futura',
  'Assistir a um jogo esportivo',
  'Montar um quebra-cabeça',
  'Visitar um festival local',
  'Assistir ao nascer do sol',
  'Assistir ao pôr do sol',
  'Ir ao cinema drive-in',
  'Explorar uma cidade nova',
  'Passeio fotográfico',
  'Ser voluntários juntos',
  'Empinar pipa',
  'Criar um álbum de recortes',
  'Andar de bicicleta',
  'Experimentar um restaurante novo',
  'Criar uma cápsula do tempo',
  'Fazer uma lista de desejos',
  'Visitar um centro de ciências',
  'Planejar um encontro surpresa',
  'Assistir a vídeos em casa',
  'Caçar conchas na praia',
  'Cozinhar um jantar a dois',
  'Realizar um sonho em comum',
  'Passeio noturno',
  'Passeio de barco',
  'Noite de vinhos',
  'Visitar uma cachoeira',
  'Fondue com karaokê',
  'Café da tarde ao ar livre',
  'Jantar temático',
  'Acampamento romântico',
  'Sessão de cinema caseiro',
  'Vinho e fogueira',
  'Escrever cartas um para o outro',
  'Trocar livros favoritos',
  'Montar uma playlist juntos',
  'Assistir ao pôr do sol em um mirante',
  'Fazer um café da manhã especial juntos',
  'Aprender uma receita totalmente nova',
  'Passear com um pet em um parque',
  'Visitar uma floricultura',
  'Conhecer um bairro novo da cidade',
  'Passeio de scooter elétrica',
  'Fazer um desafio de culinária',
  'Criar uma playlist da relação',
  'Escrever metas para o próximo ano',
  'Comprar ingredientes vendados e cozinhar',
  'Jogar perguntas e respostas sobre o casal',
  'Montar um LEGO juntos',
  'Ir a uma cafeteria temática',
  'Tomar sorvete caminhando pela cidade',
  'Visitar um observatório',
  'Passear em uma praça histórica',
  'Ver um show de luzes',
  'Fazer um tour gastronômico de sobremesas',
  'Assistir a um musical',
  'Fazer um brunch em casa',
  'Criar um mural de fotos',
  'Montar uma playlist para viajar',
  'Aprender origami juntos',
  'Fazer uma guerra de balões de água',
  'Brincar de caça ao tesouro',
  'Montar uma barraca na sala e acampar dentro de casa',
  'Fazer cookies ou brownies juntos',
  'Ir a uma loja de discos ou vinis',
  'Assistir à chuva com chocolate quente',
  'Escrever uma história juntos',
  'Fazer um tour pelas cafeterias da cidade',
  'Experimentar comidas de um país diferente',
  'Criar um desafio de fotos engraçadas',
  'Passear sem destino de carro',
  'Fazer um diário de aventuras do casal',
  'Assistir a um documentário e conversar sobre ele',
  'Piquenique no parque',
  'Jantar à luz de velas em casa',
  'Aula de culinária juntos',
  'Tarde em um café charmoso',
  'Show ao vivo',
  'Noite de jogos de tabuleiro',
  'Degustação de cervejas artesanais',
  'Escape room',
  'Aula de dança',
  'Visitar um jardim botânico',
  'Trilha ao nascer do sol',
  'Passeio de bicicleta pela cidade',
  'Dia de spa em casa',
  'Aula de pintura em tela',
  'Tarde na praia',
  'Noite de karaokê',
  'Visitar um mercado de antiguidades',
  'Tour por bairro histórico',
  'Tarde de boliche',
  'Noite de degustação de queijos',
  'Sessão de fotos urbana',
]
